name: Release DMG files
on:
  push:
    branches: [ main ]
jobs:
  build-and-release:
    name: Build and release DMG
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build DMG
        run: npm run build:mac
      
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload DMG
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.RT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/chatgpt-solo.dmg
          asset_name: chatgpt-solo.dmg
          asset_content_type: application/x-diskcopy
